apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: rhmi-s3-bucket
objects:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: ${NAME}
      namespace: ${NAMESPACE}
    stringData:
      credentialKeyID: ${AWS_ACCESS_KEY_ID}
      credentialSecretKey: ${AWS_SECRET_ACCESS_KEY}
      bucketName: ${AWS_BUCKET}
      bucketRegion: ${AWS_REGION}
parameters:
  - name: NAME
    value: "backups-s3-credentials"
  - name: NAMESPACE
    required: true
  - name: AWS_ACCESS_KEY_ID
    required: true
  - name: AWS_SECRET_ACCESS_KEY
    required: true
  - name: AWS_BUCKET
    required: true
  - name: AWS_REGION
    required: true
