# permissions for end users to edit rhmis.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rhmi-editor-role
rules:
- apiGroups:
  - integreatly.org
  resources:
  - rhmis
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - integreatly.org
  resources:
  - rhmis/status
  verbs:
  - get
