# permissions for end users to edit rhmiconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rhmiconfig-editor-role
rules:
- apiGroups:
  - integreatly.org
  resources:
  - rhmiconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - integreatly.org
  resources:
  - rhmiconfigs/status
  verbs:
  - get
